# Generated by Django 2.0.4 on 2018-11-13 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('sigla', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='EstiloMusical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('instrumento', models.CharField(max_length=50)),
                ('experiencia', models.CharField(choices=[('Amador', 'Amador'), ('Profissional', 'Profissional')], default='Amador', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='banda',
            name='estilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.EstiloMusical'),
        ),
        migrations.AddField(
            model_name='banda',
            name='musicos',
            field=models.ManyToManyField(to='music.Musico'),
        ),
    ]
